drop table word;
drop table wordhistory;

select * from word;

CREATE TABLE `WORD` (
  `SEQ` SMALLINT(5) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `ABBREVIATION` varchar(200) NOT NULL,
  `FULLNAME` varchar(255) NOT NULL,
  `SORTATION` ENUM('수식어' , '도메인') ,
  `DEFINITION` varchar(500),
  `WRITEDATE` DATE NOT NULL,
  `SYSTEM` VARCHAR(10) NOT null,
  PRIMARY KEY (`SEQ`)
);

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, DEFINITION, WRITEDATE)
VALUES('종량제봉투', 'MRBG', 'METER-RATE SYSTEM BAG', '수식어', '종량제봉투 여부를 구분하기 위해 사용', NOW());

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, WRITEDATE)
VALUES('역이동', 'RMV', 'REVERSE MOVE', '수식어', NOW());

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, WRITEDATE)
VALUES('검품', 'CHKSKU', 'CHECK STOCK KEEPING UNIT', '수식어', NOW());

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, WRITEDATE)
VALUES('혼재', 'MIX', 'MIXTURE', '수식어', NOW());

CREATE TABLE `WORDHISTORY` (
  `SEQ` INT(10) unsigned NOT NULL AUTO_INCREMENT,
  `WORDSEQ` SMALLINT(5) unsigned NOT NULL ,
  `NAME` VARCHAR(20) NOT NULL,
  `ABBREVIATION` VARCHAR(200) NOT NULL,
  `FULLNAME` VARCHAR(255) NOT NULL,
  `SORTATION` ENUM('수식어' , '도메인') NOT NULL,
  `DEFINITION` VARCHAR(500),
  `WRITEID` VARCHAR(50) NOT NULL,
  `WRITEDATE` DATE NOT NULL,
  `SYSTEM` VARCHAR(10) NOT null,
  PRIMARY KEY (`SEQ`),
  FOREIGN KEY (`WORDSEQ`) REFERENCES `WORD` (`SEQ`)
);

alter table wordhistory modify system VARCHAR(30);

select * from wordhistory;

CREATE TABLE `DOMAIN` (
  `SEQ` SMALLINT(5) unsigned NOT NULL AUTO_INCREMENT,
  `GROUPNAME` varchar(10) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `DATATYPE` VARCHAR(16) not null,
  `DATALENGTH` smallint(5) unsigned NOT null,
  `DATADECIMAL` tinyint(3) unsigned NOT null,
  `ABBREVIATION` varchar(200) REFERENCES `WORD` (`ABBREVIATION`),
  `FULLNAME` varchar(255) REFERENCES `WORD` (`FULLNAME`),
  `SYSTEM` VARCHAR(10) NOT null,
  `WRITEDATE` DATE NOT NULL,
  `DEFINITION` VARCHAR(500),
  PRIMARY KEY (`SEQ`)
);

CREATE TABLE `DOMAINHISTORY` (
  `SEQ` SMALLINT(5) unsigned NOT NULL AUTO_INCREMENT,
  `DOMAINSEQ` SMALLINT(5) unsigned REFERENCES `DOMAIN` (`SEQ`),
  `GROUPNAME` varchar(10) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `DATATYPE` VARCHAR(16) not null,
  `DATALENGTH` smallint(5) unsigned NOT null,
  `DATADECIMAL` tinyint(3) unsigned NOT null,
  `ABBREVIATION` varchar(200) REFERENCES `WORD` (`ABBREVIATION`),
  `FULLNAME` varchar(255) REFERENCES `WORD` (`FULLNAME`),
  `SYSTEM` VARCHAR(10) NOT null,
  `WRITEID` VARCHAR(50) NOT NULL,
  `WRITEDATE` DATE NOT NULL,
  `DEFINITION` VARCHAR(500),
  PRIMARY KEY (`SEQ`)
);

drop table DOMAINHISTORY;
drop table domain;

select * from domain;


