drop table word;
drop table wordhistory;

select * from word;
delete from word;

CREATE TABLE `WORD` (
  `SEQ` SMALLINT(5) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `ABBREVIATION` varchar(100) NOT NULL,
  `FULLNAME` varchar(150) NOT NULL,
  `SORTATION` ENUM('수식어' , '도메인') NOT NULL DEFAULT '수식어',
  `DEFINITION` varchar(500),
  `WRITEDATE` DATE NOT null default now(),
  `SYSTEM` ENUM('0', '1')  NOT null default '0',
  PRIMARY KEY (`SEQ`)
);

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, DEFINITION, WRITEDATE, SYSTEM)
VALUES('종량제봉투', 'MRBG', 'METER-RATE SYSTEM BAG', '수식어', '종량제봉투 여부를 구분하기 위해 사용', NOW(), '0');

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, WRITEDATE, SYSTEM)
VALUES('역이동', 'RMV', 'REVERSE MOVE', '수식어', NOW(), '0');

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, WRITEDATE, SYSTEM)
VALUES('검품', 'CHKSKU', 'CHECK STOCK KEEPING UNIT', '수식어', NOW(), '0');

INSERT INTO WORD (NAME, ABBREVIATION, FULLNAME, SORTATION, WRITEDATE, SYSTEM)
VALUES('혼재', 'MIX', 'MIXTURE', '수식어', NOW(), '0');

CREATE TABLE `WORDHISTORY` (
  `SEQ` INT(10) unsigned NOT NULL AUTO_INCREMENT,
  `WORDSEQ` SMALLINT(5) unsigned NOT NULL ,
  `NAME` VARCHAR(20) NOT NULL,
  `ABBREVIATION` VARCHAR(100) NOT NULL,
  `FULLNAME` VARCHAR(150) NOT NULL,
  `SORTATION` ENUM('수식어' , '도메인') NOT null DEFAULT '수식어',
  `DEFINITION` VARCHAR(500),
  `WRITEID` VARCHAR(50) NOT NULL,
  `WRITEDATE` DATE NOT NULL DEFAULT now(),
  `SYSTEM` ENUM('0', '1') NOT null DEFAULT '0',
  PRIMARY KEY (`SEQ`),
  FOREIGN KEY (`WORDSEQ`) REFERENCES `WORD` (`SEQ`)
);

select * from wordhistory;

CREATE TABLE `DOMAIN` (
  `SEQ` SMALLINT(5) unsigned NOT NULL AUTO_INCREMENT,
  `GROUPNAME` varchar(10) NOT NULL,
  `NAME` varchar(20) NOT null REFERENCES `WORD` (`NAME`),
  `DATATYPE` VARCHAR(16) not null,
  `DATALENGTH` smallint(5) unsigned NOT null DEFAULT 0,
  `DATADECIMAL` tinyint(3) unsigned NOT null DEFAULT 0,
  `ABBREVIATION` varchar(200) REFERENCES `WORD` (`ABBREVIATION`),
  `FULLNAME` varchar(255) REFERENCES `WORD` (`FULLNAME`),
  `SYSTEM` VARCHAR(10) NOT null DEFAULT '0',
  `WRITEDATE` DATE NOT null DEFAULT now(),
  `DEFINITION` VARCHAR(500),
  PRIMARY KEY (`SEQ`)
);

CREATE TABLE `DOMAINHISTORY` (
  `SEQ` SMALLINT(5) unsigned NOT NULL AUTO_INCREMENT,
  `DOMAINSEQ` SMALLINT(5) unsigned REFERENCES `DOMAIN` (`SEQ`),
  `GROUPNAME` varchar(10) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `DATATYPE` VARCHAR(16) not null,
  `DATALENGTH` smallint(5) unsigned NOT null DEFAULT 0,
  `DATADECIMAL` tinyint(3) unsigned NOT null DEFAULT 0,
  `ABBREVIATION` varchar(200) REFERENCES `WORD` (`ABBREVIATION`),
  `FULLNAME` varchar(255) REFERENCES `WORD` (`FULLNAME`),
  `SYSTEM` VARCHAR(10) NOT null DEFAULT '0',
  `WRITEID` VARCHAR(50) NOT NULL,
  `WRITEDATE` DATE NOT null DEFAULT now(),
  `DEFINITION` VARCHAR(500),
  PRIMARY KEY (`SEQ`)
);

drop table DOMAINHISTORY;
drop table domain;

select * from domainhistory;
